/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    work: Work;
    posts: Post;
    topics: Topic;
    enquiries: Enquiry;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    work: WorkSelect<false> | WorkSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    home: Home;
    'services-page': ServicesPage;
    'work-page': WorkPage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'journal-page': JournalPage;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'work-page': WorkPageSelect<false> | WorkPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'journal-page': JournalPageSelect<false> | JournalPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Used in the URL. Generated from the title if left blank.
   */
  slug?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * One or two sentences. Shown on the home page row.
   */
  summary: string;
  /**
   * A short line of concrete examples under the summary on the home page.
   */
  examples?: string | null;
  /**
   * Paragraph on the services index page.
   */
  indexIntro?: string | null;
  indexItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  indexLinkLabel?: string | null;
  hero: {
    heading: string;
    intro: string;
    primaryCta?: {
      label?: string | null;
      /**
       * Internal path (/contact) or full URL.
       */
      href?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      /**
       * Internal path (/contact) or full URL.
       */
      href?: string | null;
    };
  };
  figure?: {
    image?: (number | null) | Media;
    /**
     * Shown in a grey box until an image is set.
     */
    placeholder?: string | null;
    caption?: string | null;
  };
  painPoints?: {
    heading?: string | null;
    items?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  offerings?: {
    heading?: string | null;
    intro?: string | null;
    items?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  approach?: {
    heading?: string | null;
    items?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  plans?: {
    heading?: string | null;
    intro?: string | null;
    items?:
      | {
          name: string;
          price?: string | null;
          body?: string | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  relatedWork?: (number | Work)[] | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  closing?: {
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
  };
  /**
   * How this page appears in Google and when shared. Leave blank to use the page heading and intro.
   */
  seo?: {
    /**
     * Around 50 to 60 characters. " | Pixeldev" is added automatically on inner pages.
     */
    title?: string | null;
    /**
     * Around 140 to 160 characters. Mention Melbourne where it reads naturally.
     */
    description?: string | null;
    /**
     * Social share image, 1200 x 630. A branded card is generated if left blank.
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work".
 */
export interface Work {
  id: number;
  title: string;
  /**
   * Used in the URL. Generated from the title if left blank.
   */
  slug?: string | null;
  kind: 'product' | 'client' | 'anonymised';
  /**
   * Show under Selected work on the home page.
   */
  featured?: boolean | null;
  order?: number | null;
  /**
   * Short label, e.g. Plugin, WooCommerce and Square.
   */
  category?: string | null;
  summary: string;
  /**
   * If set and there is no case study, cards link here.
   */
  externalUrl?: string | null;
  image?: {
    image?: (number | null) | Media;
    /**
     * Shown in a grey box until an image is set.
     */
    placeholder?: string | null;
    caption?: string | null;
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  caseStudy?: {
    enabled?: boolean | null;
    heading?: string | null;
    intro?: string | null;
    meta?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    hero?: {
      image?: (number | null) | Media;
      /**
       * Shown in a grey box until an image is set.
       */
      placeholder?: string | null;
      caption?: string | null;
    };
    bigStats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    sections?:
      | {
          heading: string;
          body?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          steps?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          figure?: {
            image?: (number | null) | Media;
            /**
             * Shown in a grey box until an image is set.
             */
            placeholder?: string | null;
            caption?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    quote?: {
      text?: string | null;
      attribution?: string | null;
    };
    atAGlance?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    asideCta?: {
      heading?: string | null;
      body?: string | null;
      ctaLabel?: string | null;
    };
    moreWork?: (number | Work)[] | null;
  };
  /**
   * How this page appears in Google and when shared. Leave blank to use the page heading and intro.
   */
  seo?: {
    /**
     * Around 50 to 60 characters. " | Pixeldev" is added automatically on inner pages.
     */
    title?: string | null;
    /**
     * Around 140 to 160 characters. Mention Melbourne where it reads naturally.
     */
    description?: string | null;
    /**
     * Social share image, 1200 x 630. A branded card is generated if left blank.
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Used in the URL. Generated from the title if left blank.
   */
  slug?: string | null;
  publishedAt?: string | null;
  topic?: (number | null) | Topic;
  readingMinutes?: number | null;
  /**
   * Pinned at the top of the journal.
   */
  featured?: boolean | null;
  excerpt: string;
  cover?: {
    image?: (number | null) | Media;
    /**
     * Shown in a grey box until an image is set.
     */
    placeholder?: string | null;
    caption?: string | null;
  };
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  relatedService?: (number | null) | Service;
  /**
   * How this page appears in Google and when shared. Leave blank to use the page heading and intro.
   */
  seo?: {
    /**
     * Around 50 to 60 characters. " | Pixeldev" is added automatically on inner pages.
     */
    title?: string | null;
    /**
     * Around 140 to 160 characters. Mention Melbourne where it reads naturally.
     */
    description?: string | null;
    /**
     * Social share image, 1200 x 630. A branded card is generated if left blank.
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  name: string;
  /**
   * Used in the URL. Generated from the title if left blank.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  business?: string | null;
  need?: string | null;
  systems?: string | null;
  problem: string;
  budget?: string | null;
  status?: ('new' | 'replied' | 'won' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'work';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  summary?: T;
  examples?: T;
  indexIntro?: T;
  indexItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  indexLinkLabel?: T;
  hero?:
    | T
    | {
        heading?: T;
        intro?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  figure?:
    | T
    | {
        image?: T;
        placeholder?: T;
        caption?: T;
      };
  painPoints?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  offerings?:
    | T
    | {
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  approach?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  plans?:
    | T
    | {
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              name?: T;
              price?: T;
              body?: T;
              href?: T;
              id?: T;
            };
      };
  relatedWork?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  closing?:
    | T
    | {
        heading?: T;
        body?: T;
        ctaLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work_select".
 */
export interface WorkSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  featured?: T;
  order?: T;
  category?: T;
  summary?: T;
  externalUrl?: T;
  image?:
    | T
    | {
        image?: T;
        placeholder?: T;
        caption?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  caseStudy?:
    | T
    | {
        enabled?: T;
        heading?: T;
        intro?: T;
        meta?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        hero?:
          | T
          | {
              image?: T;
              placeholder?: T;
              caption?: T;
            };
        bigStats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        sections?:
          | T
          | {
              heading?: T;
              body?: T;
              steps?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              figure?:
                | T
                | {
                    image?: T;
                    placeholder?: T;
                    caption?: T;
                  };
              id?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              attribution?: T;
            };
        atAGlance?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        asideCta?:
          | T
          | {
              heading?: T;
              body?: T;
              ctaLabel?: T;
            };
        moreWork?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  topic?: T;
  readingMinutes?: T;
  featured?: T;
  excerpt?: T;
  cover?:
    | T
    | {
        image?: T;
        placeholder?: T;
        caption?: T;
      };
  content?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedService?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  business?: T;
  need?: T;
  systems?: T;
  problem?: T;
  budget?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  ownerName?: string | null;
  /**
   * Footer blurb and default meta description.
   */
  tagline?: string | null;
  locationLine?: string | null;
  email?: string | null;
  supportEmail?: string | null;
  linkedin?: string | null;
  abn?: string | null;
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  headerCtaLabel?: string | null;
  /**
   * Used for the structured data Google reads for local search. Leave the street address blank to show only the suburb.
   */
  business?: {
    /**
     * Include the country code, e.g. +61 400 000 000.
     */
    phone?: string | null;
    streetAddress?: string | null;
    locality?: string | null;
    region?: string | null;
    postcode?: string | null;
    areaServed?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional, e.g. $$.
     */
    priceRange?: string | null;
  };
  seo?: {
    /**
     * Used when a page has no description of its own.
     */
    defaultDescription?: string | null;
    /**
     * The one-paragraph summary at the top of /llms.txt.
     */
    llmsSummary?: string | null;
  };
  products?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    /**
     * Small label above the heading. A good place for what you do and where.
     */
    eyebrow?: string | null;
    heading: string;
    intro: string;
    primaryCta?: {
      label?: string | null;
      /**
       * Internal path (/contact) or full URL.
       */
      href?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      /**
       * Internal path (/contact) or full URL.
       */
      href?: string | null;
    };
    facts?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  figure?: {
    image?: (number | null) | Media;
    /**
     * Shown in a grey box until an image is set.
     */
    placeholder?: string | null;
    caption?: string | null;
  };
  servicesSection?: {
    eyebrow?: string | null;
    note?: string | null;
  };
  workSection?: {
    heading?: string | null;
    linkLabel?: string | null;
  };
  process?: {
    heading?: string | null;
    steps?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  about?: {
    heading?: string | null;
    body?: string | null;
    linkLabel?: string | null;
    photo?: {
      image?: (number | null) | Media;
      /**
       * Shown in a grey box until an image is set.
       */
      placeholder?: string | null;
      caption?: string | null;
    };
  };
  testimonial?: {
    quote?: string | null;
    attribution?: string | null;
  };
  closing?: {
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
  };
  /**
   * How this page appears in Google and when shared. Leave blank to use the page heading and intro.
   */
  seo?: {
    /**
     * Around 50 to 60 characters. " | Pixeldev" is added automatically on inner pages.
     */
    title?: string | null;
    /**
     * Around 140 to 160 characters. Mention Melbourne where it reads naturally.
     */
    description?: string | null;
    /**
     * Social share image, 1200 x 630. A branded card is generated if left blank.
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  engagement?: {
    heading?: string | null;
    intro?: string | null;
    options?:
      | {
          title: string;
          price?: string | null;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  closing?: {
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
  };
  /**
   * How this page appears in Google and when shared. Leave blank to use the page heading and intro.
   */
  seo?: {
    /**
     * Around 50 to 60 characters. " | Pixeldev" is added automatically on inner pages.
     */
    title?: string | null;
    /**
     * Around 140 to 160 characters. Mention Melbourne where it reads naturally.
     */
    description?: string | null;
    /**
     * Social share image, 1200 x 630. A branded card is generated if left blank.
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page".
 */
export interface WorkPage {
  id: number;
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  products?: {
    heading?: string | null;
    intro?: string | null;
  };
  clients?: {
    heading?: string | null;
    intro?: string | null;
    note?: string | null;
  };
  anonymised?: {
    heading?: string | null;
    intro?: string | null;
  };
  /**
   * How this page appears in Google and when shared. Leave blank to use the page heading and intro.
   */
  seo?: {
    /**
     * Around 50 to 60 characters. " | Pixeldev" is added automatically on inner pages.
     */
    title?: string | null;
    /**
     * Around 140 to 160 characters. Mention Melbourne where it reads naturally.
     */
    description?: string | null;
    /**
     * Social share image, 1200 x 630. A branded card is generated if left blank.
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  body?: string | null;
  photo?: {
    image?: (number | null) | Media;
    /**
     * Shown in a grey box until an image is set.
     */
    placeholder?: string | null;
    caption?: string | null;
  };
  facts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  background?: {
    heading?: string | null;
    items?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  promises?: {
    heading?: string | null;
    items?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  solo?: {
    heading?: string | null;
    body?: string | null;
  };
  closing?: {
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
  };
  /**
   * How this page appears in Google and when shared. Leave blank to use the page heading and intro.
   */
  seo?: {
    /**
     * Around 50 to 60 characters. " | Pixeldev" is added automatically on inner pages.
     */
    title?: string | null;
    /**
     * Around 140 to 160 characters. Mention Melbourne where it reads naturally.
     */
    description?: string | null;
    /**
     * Social share image, 1200 x 630. A branded card is generated if left blank.
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  form?: {
    needOptions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    budgetOptions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    submitLabel?: string | null;
    submitNote?: string | null;
    successHeading?: string | null;
    successBody?: string | null;
  };
  nextSteps?: {
    heading?: string | null;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  aside?: {
    directHeading?: string | null;
    directNote?: string | null;
    supportHeading?: string | null;
    supportNote?: string | null;
  };
  /**
   * How this page appears in Google and when shared. Leave blank to use the page heading and intro.
   */
  seo?: {
    /**
     * Around 50 to 60 characters. " | Pixeldev" is added automatically on inner pages.
     */
    title?: string | null;
    /**
     * Around 140 to 160 characters. Mention Melbourne where it reads naturally.
     */
    description?: string | null;
    /**
     * Social share image, 1200 x 630. A branded card is generated if left blank.
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page".
 */
export interface JournalPage {
  id: number;
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  /**
   * How this page appears in Google and when shared. Leave blank to use the page heading and intro.
   */
  seo?: {
    /**
     * Around 50 to 60 characters. " | Pixeldev" is added automatically on inner pages.
     */
    title?: string | null;
    /**
     * Around 140 to 160 characters. Mention Melbourne where it reads naturally.
     */
    description?: string | null;
    /**
     * Social share image, 1200 x 630. A branded card is generated if left blank.
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  ownerName?: T;
  tagline?: T;
  locationLine?: T;
  email?: T;
  supportEmail?: T;
  linkedin?: T;
  abn?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCtaLabel?: T;
  business?:
    | T
    | {
        phone?: T;
        streetAddress?: T;
        locality?: T;
        region?: T;
        postcode?: T;
        areaServed?:
          | T
          | {
              name?: T;
              id?: T;
            };
        priceRange?: T;
      };
  seo?:
    | T
    | {
        defaultDescription?: T;
        llmsSummary?: T;
      };
  products?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        facts?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  figure?:
    | T
    | {
        image?: T;
        placeholder?: T;
        caption?: T;
      };
  servicesSection?:
    | T
    | {
        eyebrow?: T;
        note?: T;
      };
  workSection?:
    | T
    | {
        heading?: T;
        linkLabel?: T;
      };
  process?:
    | T
    | {
        heading?: T;
        steps?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        heading?: T;
        body?: T;
        linkLabel?: T;
        photo?:
          | T
          | {
              image?: T;
              placeholder?: T;
              caption?: T;
            };
      };
  testimonial?:
    | T
    | {
        quote?: T;
        attribution?: T;
      };
  closing?:
    | T
    | {
        heading?: T;
        body?: T;
        ctaLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  engagement?:
    | T
    | {
        heading?: T;
        intro?: T;
        options?:
          | T
          | {
              title?: T;
              price?: T;
              body?: T;
              id?: T;
            };
      };
  closing?:
    | T
    | {
        heading?: T;
        body?: T;
        ctaLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page_select".
 */
export interface WorkPageSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  products?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  clients?:
    | T
    | {
        heading?: T;
        intro?: T;
        note?: T;
      };
  anonymised?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  body?: T;
  photo?:
    | T
    | {
        image?: T;
        placeholder?: T;
        caption?: T;
      };
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  background?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  promises?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  solo?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  closing?:
    | T
    | {
        heading?: T;
        body?: T;
        ctaLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  form?:
    | T
    | {
        needOptions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        budgetOptions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        submitLabel?: T;
        submitNote?: T;
        successHeading?: T;
        successBody?: T;
      };
  nextSteps?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  aside?:
    | T
    | {
        directHeading?: T;
        directNote?: T;
        supportHeading?: T;
        supportNote?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page_select".
 */
export interface JournalPageSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}